In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas.io.sql
import pyodbc
import csv
import pymysql
# import mysql.connector
# from mysql.connector import Error
# import MySQLdb
# !pip install PyMySQL
# !pip install pyodbc
import xlrd
#server = 'XXXXX'
#db = 'XXXXXdb'
# https://stackoverflow.com/questions/45800460/how-to-use-mysqldb-is-connected-to-check-an-active-mysql-connection-using-pyth
# create Connection and Cursor objects
# conn = pyodbc.connect('DRIVER={SQL Server};SERVER=' + server + ';DATABASE=' + db + ';Trusted_Connection=yes')
# cursor = conn.cursor()
connection = pymysql.connect(host='127.0.0.1',database='inventory_db',user='boratonaj',password='legendary@1983')
try:                                 
    if connection.open:
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if connection.open:
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

In [ ]:
query1 = """  
    CREATE TABLE IF NOT EXISTS customer_orders_rank_tb (
      customerid INT(11) NOT NULL,
      orderid INT(11) NOT NULL,
      rank_id INT(11) NOT NULL,
      PRIMARY KEY (orderid)
      )
    """

In [ ]:
query2 = """
        CREATE TABLE IF NOT EXISTS customer_orders_tb (
          createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          orderid INT(11) NOT NULL,
          restaurantstatus VARCHAR(45),
          paymentmethod VARCHAR(45),
          subtotal DECIMAL(45),
          customerid INT(11) NOT NULL,
          restaurantname VARCHAR(150) ,
          customeraddressprovince VARCHAR(45),
          restaurantacceptedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          foodpreparedpromised TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          podactual TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (orderid)
          )
         """

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas.io.sql
import pyodbc
import csv
import pymysql

try:
    connection = pymysql.connect(host='127.0.0.1',database='inventory_db',user='boratonaj',password='legendary@1983')
    cursor = connection.cursor()
    cursor.execute(query1)
    cursor.execute(query2)
    print("Table created successfully ")
    
except pymysql.Error as error:
    print("Failed to create table in MySQL: {}".format(error))
finally:
    if (connection.open):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

In [ ]:
insert_query1 = """
INSERT INTO customer_orders_tb (
   createdat,
    orderid,
    restaurantstatus,
    paymentmethod,
    subtotal,
    customerid,
    restaurantname,
    customeraddressprovince,
    restaurantacceptedat,
    foodpreparedpromised,
    podactual
) 
VALUES (%s, %s, %s, %s,%s, %s, %s, %s,%s, %s, %s)
"""

insert_query2 = """
INSERT INTO [inventory_db].[customer_orders_rank_tb] (
    customerid,
    orderid,
    rank_id
) VALUES (?, ?, ?)"""

In [ ]:
# !pip install xlsx2csv
from xlsx2csv import Xlsx2csv
Xlsx2csv("tables.xlsx", outputencoding="utf-8").convert("Orders.csv")
data = 'Orders.csv'

csv_data = pd.read_csv(data, delimiter = ',')
for row in csv_data:
    print(row)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas.io.sql
import pyodbc
import csv
import pymysql


try:
    connection = pymysql.connect(host='127.0.0.1',
                                 database='inventory_db',
                                 user='boratonaj',
                                 password='legendary@1983')
    cursor = connection.cursor()
    
    print("Loading Data")
    # read data
#     data = r'C:Users\OAjayi\Desktop\Data_science\Zindi\Woman_big_Data\MR_D_Takealot\tables\Orders.csv'
    
    csv_data = csv.DictReader(data, delimiter = ',')
    for row in csv_data:
        cursor.execute(insert_query1,row)
#         cursor.execute(insert_query2,row)
    connection.commit()
    print("Record inserted successfully into customer order table")

except pymysql.Error as error:
    print("Failed to insert into customer order table in MySQL: {}".format(error))

finally:
    if (connection.open):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

In [ ]:
  from __future__ import print_function
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas.io.sql
import pyodbc
import csv
import pymysql

print("Enter  File  To Be Export")

# cursor = conn.cursor()
# #sql = 'CREATE DATABASE test1'
# sql ='''DROP TABLE IF EXISTS `test1`; CREATE TABLE test1 (policyID int, statecode varchar(255), county varchar(255))'''
# cursor.execute(sql)

with open('Orders_rank.csv') as csvfile:
    reader = csv.DictReader(csvfile, delimiter = ',')
    for row in reader:
#         print(row['policyID'], row['statecode'], row['county'])
        # insert
        conn = pymysql.connect(host='127.0.0.1',
                                 database='inventory_db',
                                 user='boratonaj',
                                 password='legendary@1983')
        
        
        sql_statement =  """
                            INSERT INTO customer_orders_rank_tb (
                            customerid,
                            orderid,
                            rank_id) 
                            VALUES (%s, %s, %s)
                            """

        cur = conn.cursor()
        cur.executemany(sql_statement,[(str(row['customerid']), str(row['orderid']), str(row['rank_id']))])
        conn.escape_string(sql_statement)
        conn.commit()
    print(cursor.rowcount, "Inserting into table successfully")

In [ ]:
  from __future__ import print_function
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas.io.sql
import pyodbc
import csv
import pymysql

print("Enter  File  To Be Export")

# cursor = conn.cursor()
# #sql = 'CREATE DATABASE test1'
# sql ='''DROP TABLE IF EXISTS `test1`; CREATE TABLE test1 (policyID int, statecode varchar(255), county varchar(255))'''
# cursor.execute(sql)

with open('Orders.csv') as csvfile:
    reader = csv.DictReader(csvfile, delimiter = ',')
    for row in reader:
#         print(row['policyID'], row['statecode'], row['county'])
        # insert
        conn = pymysql.connect(host='127.0.0.1',
                                 database='inventory_db',
                                 user='boratonaj',
                                 password='legendary@1983')
        
        
        sql_statement = """
                            INSERT INTO customer_orders_tb (
                               createdat,
                                orderid,
                                restaurantstatus,
                                paymentmethod,
                                subtotal,
                                customerid,
                                restaurantname,
                                customeraddressprovince,
                                restaurantacceptedat,
                                foodpreparedpromised,
                                podactual
                            ) 
                            VALUES (%s, %s, %s, %s, %s, %s, %s,  %s, %s, %s, %s)
                            """
        cur = conn.cursor()
        cur.executemany(sql_statement,[(str(row['createdat']), str(row['orderid']), str(row['restaurantstatus']),
                                        str(row['paymentmethod']), str(row['subtotal']), str(row['customerid']),
                                        str(row['restaurantname']), str(row['customeraddressprovince']), str(row['restaurantacceptedat']),
                                        str(row['foodpreparedpromised']), str(row['podactual'])
                                       )])
        conn.escape_string(sql_statement)
        conn.commit()
    print(cursor.rowcount, "Inserting into table successfully")